paths:
  train_dir: /workspace/SynVA_V1/derived_data/TreesSplines_k_count_500depth_healthy_decap_dense_v1_prepared/train
  val_dir:   /workspace/SynVA_V1/derived_data/TreesSplines_k_count_500depth_healthy_decap_dense_v1_prepared/val
  test_dir:  /workspace/SynVA_V1/derived_data/TreesSplines_k_count_500depth_healthy_decap_dense_v1_prepared/test

  output_root:   /workspace/SynVA_V1/derived_data/TreesSplines_k_count_500depth_healthy_decap_dense_v1_prepared_biffilter_v2
  metadata_path: /workspace/SynVA_V1/derived_data/TreesSplines_k_count_500depth_healthy_decap_dense_v1_prepared_biffilter_v2/filter_short_segments_metadata.json

params:
  pattern: "*.npy"
  k: 39
  alpha_cont: 1.0
  alpha_bif: 0.30
  eps_radius: 1.0e-6
