paths:
  train_dir: /workspace/SynVA_V1/derived_data/test_extra/biffilter_v2_norm/test
  val_dir:   /workspace/SynVA_V1/derived_data/test_extra/biffilter_v2_norm/test
  test_dir:  /workspace/SynVA_V1/derived_data/test_extra/biffilter_v2_norm/test
  output_root:   /workspace/SynVA_V1/derived_data/test_extra/biffilter_v2_norm_relpos_nodecp_v1
  metadata_path: /workspace/SynVA_V1/derived_data/test_extra/biffilter_v2_norm_relpos_nodecp_v1/local_geometry_metadata.json

params:
  pattern: "*.npy"
  overwrite: false
  position_slice: [1, 4]
  control_point_slices: [[4, 12], [12, 20], [20, 28]]
  relative_positions: true
  node_local_control_points: true
